version: '2.1'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    container_name: nsqd
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis'
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  dumper-service:
    container_name: dumper-service
    build: ./dumper
    volumes:
      - './dumper:/data/app'
    depends_on:
      redis:
        condition: service_healthy
      nsqd:
        condition: service_started
    links:
      - redis
      - nsqd

  backend-service:
    container_name: backend-service
    build: ./dashboard-backend
    volumes:
      - './dashboard-backend:/data/app'
    ports:
      - '3001:3001'
    depends_on:
      redis:
        condition: service_healthy
    links:
      - redis

  frontend-service:
    container_name: frontend-service
    build: ./dashboard-frontend
    volumes:
      - './dashboard-frontend:/data/app'
    ports:
      - '3000:3000'
    depends_on:
      - backend-service
    links:
      - backend-service

volumes:
  redis_data:
    driver: local
